---
- name: Ansible Playbook for configuring brand new Raspberry Pi

  hosts: rpis
  roles:
    - common
#    - openhab
#    - mysql
#    - sonarr
  remote_user: ansible
  become: yes
  vars:
    update_admin_users: yes
    upgrade_all_apt_pkgs: no
    add_mount_for_usb: yes
    install_vim: yes
    configure_wifi: yes
    configure_samba: yes
    configure_openvpn: yes
