---
# handlers file for roles/common

- name: restart server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: Restart Samba
  service:
    name: smbd
    state: restarted
