---
# tasks file for roles/common-linux

- include_vars: vars_admin_users.yml

- name: Admin Users | Creating groups
  group: name="{{ item }}"
  with_items: "{{ groups_to_create }}"
  tags: ['users','groups','configuration']

- name: Admin Users | Per-user group creation
  group: name="{{ item.name }}"
         gid="{{ item.uid | default(omit) }}"
  with_items: "{{ admin_users }}"
  when: "{{ users_create_per_user_group }}"
  tags: ['users','configuration']

- name: Admin Users | Admin User creation
  user: name="{{ item.name }}"
        group="{{ item.name if users_create_per_user_group
            else users_group }}"
        groups="{{ item.groups | default(omit) }}"
        shell="{{ item.shell if item.shell is defined else users_default_shell }}"
        password="{{ item.password | default(omit) }}"
        comment="{{ item.comment | default(omit) }}"
        uid="{{ item.uid | default(omit) }}"
        createhome="{{ 'yes' if users_create_homedirs else 'no' }}"
        update_password=always
        state="{{ item.state }}"
  with_items: "{{ admin_users }}"
  tags: ['users','configuration']

- name: Add user public SSH key
  authorized_key: user="{{ item.name }}" key="{{item.ssh_key_rsa}}"
  with_items: "{{ admin_users }}"
  become: yes
  no_log: true

- name: Admin Users | Deleted user removal
  user: name="{{ item.name }}" state=absent
  with_items: "{{ users_deleted }}"
  tags: ['users','configuration']

- name: Admin Users | Deleted per-user group removal
  group: name="{{ item.name }}" state=absent
  with_items: "{{ users_deleted }}"
  when: "{{ users_create_per_user_group }}"
  tags: ['users','configuration']
