---
# tasks file for roles/common

- include_tasks: admin_users.yml
  when: update_admin_users

- include_tasks: apt.yml
  when: upgrade_all_apt_pkgs

- include_tasks: mount_usb.yml
  when:  add_mount_for_usb

- include_tasks: vim.yml
  when:  install_vim

- include_tasks: wifi.yml
  when:  configure_wifi

- include_tasks: samba.yml
  when:  configure_samba

- include_tasks: openvpn.yml
  when:  configure_openvpn
