---
- name: Vim | Make sure vim-tiny is uninstalled
  apt:
    name: vim-tiny
    state: absent
    purge: true

- name: Vim | Make sure vim is installed
  apt:
    name: vim
    state: present
#    update_cache: yes

- name: Vim | Make sure htop is installed
  apt:
    name: htop
    state: present
#    update_cache: yes
