---
# vars file for admin_users

# Create a group for every user and make that their primary group
users_create_per_user_group: true

# If we're not creating a per-user group, then this is the group all users
# belong to
users_group: users

# The default shell for a user if none is specified
users_default_shell: /bin/bash

# Create home dirs for new users? Set this to false if you manage home
# directories in some other way.
users_create_homedirs: true

# Lists of users to create and delete
admin_users:
- name: root
  password: "$6$rounds=656000$FzwEAl9oLbr9wO.G$vZN8CCCZWUjPyuQcPjmsq5y82dZJS.DY1N5uxzAJQViGLtqkfIfUvfmpWzFcIvAMQEN9B/fgyY/mYPv9kC5DY0"
  state: "present"
  groups: "root"
  comment: root

- name: pi
  password: "$6$rounds=656000$FzwEAl9oLbr9wO.G$vZN8CCCZWUjPyuQcPjmsq5y82dZJS.DY1N5uxzAJQViGLtqkfIfUvfmpWzFcIvAMQEN9B/fgyY/mYPv9kC5DY0"
  state: "present"
  groups: "adm"
  comment: pi
  ssh_key_rsa: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIG0fvq7eTShh4xTgr1uB8WYoGRg2+6hHgvA/yHOzLk2YfGpRoRnh7eeaX4FekMq2p0xNX0rdFBI56mC44VQk0/8Lqap3pZStdXW5nHQ9LIrr6yIXgwOhJEtM+9TWaTHXK/D9vdLIiEspdE1+iF+7fqicxtul3KQeZkMt3k+HigZNneOhBx/vgkHRrJ2baTX6cDhvdh9Ir2cfJP4SuwiVbbCeQJyZLv2VluFs4L1wp4PdbbicOBmNByMDOGuhr4JuuGhl5n5Kbv7dbNhUfORQkkbmaSKPt4ITTG0khuTFcISltHItSNQZPUjTyrmvOw/OY6OCpbWxAC8Zwrsu45nwH doug@dougspi"

- name: dpearson
  password: "$6$rounds=656000$FzwEAl9oLbr9wO.G$vZN8CCCZWUjPyuQcPjmsq5y82dZJS.DY1N5uxzAJQViGLtqkfIfUvfmpWzFcIvAMQEN9B/fgyY/mYPv9kC5DY0"
  state: "present"
  groups: "adm"
  comment: "Douglas Pearson"
  ssh_key_rsa: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIG0fvq7eTShh4xTgr1uB8WYoGRg2+6hHgvA/yHOzLk2YfGpRoRnh7eeaX4FekMq2p0xNX0rdFBI56mC44VQk0/8Lqap3pZStdXW5nHQ9LIrr6yIXgwOhJEtM+9TWaTHXK/D9vdLIiEspdE1+iF+7fqicxtul3KQeZkMt3k+HigZNneOhBx/vgkHRrJ2baTX6cDhvdh9Ir2cfJP4SuwiVbbCeQJyZLv2VluFs4L1wp4PdbbicOBmNByMDOGuhr4JuuGhl5n5Kbv7dbNhUfORQkkbmaSKPt4ITTG0khuTFcISltHItSNQZPUjTyrmvOw/OY6OCpbWxAC8Zwrsu45nwH doug@dougspi"

users_deleted: []

groups_to_create: []
